<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
 
  'Pcnt Name' => 'name',
  'Pdcm Hidded' => 'Hidded',
  'Pdcm Name' => 'Name',
  'Ppcn Modified' => 'Modified',
  'Ppcn Notes' => 'Notes',
  'Ppcn Pcnt Type' => 'Type',
  'Ppcn Person Contact' => 'Person Contact',
  'Ppcn Person Contacts' => 'Person Contacts',
  'Ppcn Value' => 'Value',
  'Pprs First Name' => 'First Name',
  'Pprs People' => 'People',
  'Pprs Person' => 'Person',
  'Pprs Second Name' => 'Second Name',
  'Ppxd Expire Date' => 'Expire Date',
  'Ppxd Issue Date' => 'Issue Date',
  'Ppxd Notes' => 'Notes',
  'Ppxd Number' => 'Number',
  'Ppxd Pdcm' => 'Type',
  'Ppxd Person Xdocument' => 'Person document',
  'Ppxd Person Xdocuments' => 'Person documents',
  'Ppxd Status' => 'Status',
  'Ppxs Notes' => 'Notes',
  'Ppxs Person Xsetting' => 'Settings',
  'Ppxs Psty' => 'Type',
  'Ppxs Value' => 'Value',
  'Ppxt Person Xtype' => 'Person Group',
  'Ppxt Person Xtypes' => 'Persons Groups',
  'Ppxt Ptyp' => 'Group',
  'Ptyp Hidden' => 'Hidden',
  'Ptyp Name' => 'Name',
  'Ptyp Type' => 'Type',
  'Ptyp Types' => 'Types',
  'relation.CcucUserCompanies' => 'Use Companies',
  'relation.PpcnPcntType' => 'Contact types',
  'relation.PpcnPersonContacts' => 'Person contacts',
  'relation.PpcnPprs' => 'Persons',
  'relation.PpxdPdcm' => 'Documents',
  'relation.PpxdPersonXDocuments' => 'Person documents',
  'relation.PpxdPprs' => 'Persons',
  'relation.PpxtPersonXTypes' => 'Persons Groups',
  'relation.PpxtPprs' => 'Persons',
  'relation.PpxtPtyp' => 'Person Group',
  'relation.Profile' => 'Person profile',
);
