<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Amount' => 'Suma',
  'Base Payment Before' => 'Bazė Išankstiniai mokėjimai',
  'Base Total' => 'Bazė',
  'Base VAT' => 'PVM',
  'Base amount' => 'Bazės suma',
  'Base currency' => 'Bazės valiuta',
  'Bprd' => '',
  'Budget Date' => 'Biudžetas data',
  'Credit account' => '',
  'Currency' => 'Valiuta',
  'Date' => 'Data',
  'Debet account' => '',
  'Description' => 'Aprašymas',
  'Due Date' => '',
  'Is Paid' => 'Apmokėtas',
  'Issuer' => 'Išdavė',
  'Measure' => 'Matas',
  'Not Paid' => 'Neapmokėjo',
  'Notes' => 'Pastabos',
  'Number' => 'Numeris',
  'Partly Paid' => 'Dalinis apmokėjimas',
  'Payer' => 'Mokėtojas',
  'Payment status' => 'Mokėjimo būsena',
  'Price' => 'Kaina',
  'Quantity' => 'Kiekis',
  'REF' => '',
  'REF ID' => '',
  'Registred' => 'Registruotas',
  'Series' => 'Serija',
  'Status' => 'Būsena',
  'Total' => 'Viso',
  'Unit price' => 'Kaina už vienetą',
  'VAT' => 'PVM',
  'VAT amount' => 'Suma PVM',

);
